name: The Midnite Piddler
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64229
title: The Midnite Piddler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#acacab'
    - '#858587'
    - '#542d0f'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
