name: The Midnite Piddler
favicon: null
layout_spectrum: 0.2379227066412568
typography_spectrum: 0.6611388761084527
title: The Midnite Piddler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.94621576461941
  lightness: 0.33024735911749303
  saturation: 0.8484740541316569
  rhythmicContrast: 0.09239525604061782
purpose: []
